AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'spec/fixtures/**/*'
    - '**/.**'

Documentation:
  Enabled: false

LineLength:
  Max: 100

Style/SignalException:
  Enabled: false

Style/AndOr:
  # Whether `and` and `or` are banned only in conditionals (conditionals)
  # or completely (always).
  EnforcedStyle: conditionals
