inherit_from: .rubocop_rails.yml

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'spec/fixtures/**/*'
    - '**/.**'

RSpec/FilePath:
  Exclude:
    - 'spec/features/**/*'

Documentation:
  Enabled: false

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 100

Style/SignalException:
  Enabled: false

Style/AndOr:
  # Whether `and` and `or` are banned only in conditionals (conditionals)
  # or completely (always).
  EnforcedStyle: conditionals
